FROM node:22-alpine
ARG SERVICE_NAME
WORKDIR /app
COPY . .
RUN npm install --prefix services/${SERVICE_NAME}
RUN ln -s /app/services/${SERVICE_NAME}/node_modules /app/node_modules
RUN npm run build --prefix services/${SERVICE_NAME}
WORKDIR /app/services/${SERVICE_NAME}
CMD ["npm", "run", "start:prod"]
