upstream user_auth  { server user-auth:4001; }
upstream catalog    { server catalog:4002; }
upstream adoption   { server adoption:4003; }
upstream chat       { server chat:4004; }
upstream match      { server match:4005; }
upstream reports    { server reports:4006; }

server {
    listen 80;

    # Headers de proxy padrão
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /v1/health     { proxy_pass http://user_auth; }
    location /v1/users      { proxy_pass http://user_auth; }
    location /v1/pets       { proxy_pass http://catalog; }
    location /v1/adoptions  { proxy_pass http://adoption; }
    location /v1/chat       { proxy_pass http://chat; }
    location /v1/match      { proxy_pass http://match; }
    location /v1/reports    { proxy_pass http://reports; }

    # Swagger por serviço
    location /docs/user-auth  { rewrite ^/docs/user-auth(.*) /v1/docs$1 break; proxy_pass http://user_auth; }
    location /docs/catalog    { rewrite ^/docs/catalog(.*) /v1/docs$1 break; proxy_pass http://catalog; }
    location /docs/adoption   { rewrite ^/docs/adoption(.*) /v1/docs$1 break; proxy_pass http://adoption; }
    location /docs/chat       { rewrite ^/docs/chat(.*) /v1/docs$1 break; proxy_pass http://chat; }
    location /docs/match      { rewrite ^/docs/match(.*) /v1/docs$1 break; proxy_pass http://match; }
    location /docs/reports    { rewrite ^/docs/reports(.*) /v1/docs$1 break; proxy_pass http://reports; }
}
